"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Circle, Hand, Radio, RefreshCw, Swords, X } from "lucide-react";
import { toast } from "sonner";

type Player = { id: string; name: string };
type GameKey = "tic-tac-toe" | "rock-paper-scissors-shoot";
type Match = { id: string; gameKey: GameKey; playerOneId: string; playerTwoId: string; playerOne: Player; playerTwo: Player; currentTurn: "player-one" | "player-two"; status: "active" | "completed"; result: string | null; state: Record<string, unknown>; moves: { turn: number }[] };
const LABEL: Record<GameKey, string> = { "tic-tac-toe": "Tic-Tac-Toe", "rock-paper-scissors-shoot": "Rock Paper Scissors" };
const CHOICES = ["rock", "paper", "scissors"] as const;

export function FamilyMultiplayerGame({ gameKey, player, opponents, onBack }: { gameKey: GameKey; player: Player; opponents: Player[]; onBack: () => void }) {
  const [matches, setMatches] = useState<Match[]>([]); const [openedId, setOpenedId] = useState<string | null>(null); const [opponentId, setOpponentId] = useState(""); const [busy, setBusy] = useState(false); const [live, setLive] = useState(false);
  const refresh = useCallback(async () => { const response = await fetch(`/api/family-games?memberId=${encodeURIComponent(player.id)}`); const data = await response.json().catch(() => null); if (!response.ok) return toast.error(data?.error ?? "Could not load family games"); setMatches((data.matches ?? []).filter((match: Match) => match.gameKey === gameKey)); }, [gameKey, player.id]);
  useEffect(() => { void refresh(); }, [refresh]);
  const match = matches.find((item) => item.id === openedId) ?? null;
  const myPosition = match?.playerOneId === player.id ? "player-one" : match?.playerTwoId === player.id ? "player-two" : null;
  const myTurn = Boolean(match && match.status === "active" && myPosition === match.currentTurn);

  useEffect(() => { if (!openedId) return; const protocol = window.location.protocol === "https:" ? "wss:" : "ws:"; const socket = new WebSocket(`${protocol}//${window.location.host}/ws/chess`); socket.addEventListener("open", () => { setLive(true); socket.send(JSON.stringify({ type: "subscribe", matchId: openedId })); }); socket.addEventListener("message", (event) => { try { const message = JSON.parse(event.data); if (message.type === "match-updated" && message.matchId === openedId) void refresh(); } catch { /* Ignore malformed websocket messages. */ } }); socket.addEventListener("close", () => setLive(false)); socket.addEventListener("error", () => setLive(false)); const poll = window.setInterval(() => void refresh(), 5000); return () => { window.clearInterval(poll); socket.close(); setLive(false); }; }, [openedId, refresh]);

  async function request(body: Record<string, unknown>) { setBusy(true); const response = await fetch("/api/family-games", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json().catch(() => null); setBusy(false); if (!response.ok) { toast.error(data?.error ?? "Could not update the game"); await refresh(); return null; } await refresh(); return data; }
  async function start() { const data = await request({ action: "start", gameKey, playerOneId: player.id, playerTwoId: opponentId }); if (data?.match?.id) setOpenedId(data.match.id); }
  async function move(payload: Record<string, unknown>) { if (!match || !myTurn || busy) return; await request({ action: "move", matchId: match.id, memberId: player.id, ...payload }); }
  const opponent = match ? (match.playerOneId === player.id ? match.playerTwo : match.playerOne) : null;

  if (match) {
    const state = match.state ?? {}; const board = Array.isArray(state.board) ? state.board as Array<string | null> : Array(9).fill(null); const lastRound = state.lastRound as { playerOneChoice?: string; playerTwoChoice?: string; result?: string } | null;
    return <section className="rounded-3xl bg-white p-5 shadow-sm"><button type="button" onClick={() => setOpenedId(null)} className="text-sm font-black text-violet-700">← {LABEL[gameKey]} games</button><div className="mt-3 flex flex-wrap items-start justify-between gap-2"><div><h2 className="flex items-center gap-2 text-2xl font-black text-slate-800"><Swords className="text-violet-700"/> {match.playerOne.name} vs {match.playerTwo.name}</h2><p className="mt-1 text-sm font-bold text-slate-500">{match.status === "completed" ? `Game complete · ${match.result === "draw" ? "draw" : match.result === "player-one-won" ? `${match.playerOne.name} won` : `${match.playerTwo.name} won`}` : myTurn ? "Your turn!" : `Waiting for ${opponent?.name}'s move`}</p></div><button type="button" onClick={() => void refresh()} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-black text-slate-700"><RefreshCw size={15} className="mr-1 inline"/>Refresh</button></div>{gameKey === "tic-tac-toe" ? <div className="mx-auto mt-6 grid max-w-sm grid-cols-3 gap-2">{board.map((mark, index) => <button key={index} type="button" disabled={!myTurn || Boolean(mark) || busy} onClick={() => void move({ index })} className="aspect-square rounded-2xl bg-violet-50 text-5xl font-black text-violet-700 transition hover:bg-violet-100 disabled:cursor-default disabled:opacity-80">{mark === "X" ? <X className="mx-auto" size={48}/> : mark === "O" ? <Circle className="mx-auto" size={42}/> : ""}</button>)}</div> : <div className="mt-6"><div className="rounded-2xl bg-red-50 p-4 text-center font-black text-red-800">First to 3 wins · {match.playerOne.name} {Number(state.playerOneScore ?? 0)} · {match.playerTwo.name} {Number(state.playerTwoScore ?? 0)} · {Number(state.ties ?? 0)} ties</div>{lastRound && <p className="mt-3 text-center font-bold text-slate-600">Last round: {lastRound.playerOneChoice} vs {lastRound.playerTwoChoice} · {lastRound.result === "tie" ? "Tie" : lastRound.result === "player-one" ? `${match.playerOne.name} won` : `${match.playerTwo.name} won`}</p>}{myTurn && match.status === "active" ? <div className="mt-4 grid grid-cols-3 gap-3">{CHOICES.map((choice) => <button key={choice} type="button" disabled={busy} onClick={() => void move({ choice })} className="rounded-2xl bg-red-100 p-4 text-lg font-black capitalize text-red-900 transition hover:bg-red-200">{choice}</button>)}</div> : <p className="mt-4 text-center text-sm font-bold text-slate-500">{myPosition === "player-one" && match.currentTurn === "player-two" ? "Your choice is locked in. Waiting for the reveal." : "Waiting for the other player."}</p>}</div>}<p className={`mt-5 text-xs font-bold ${live ? "text-emerald-600" : "text-amber-600"}`}><Radio className="mr-1 inline size-3"/>{live ? "Live connection" : "Checking for moves every 5 seconds"}</p></section>;
  }

  return <section className="rounded-3xl bg-white p-5 shadow-sm"><button type="button" onClick={onBack} className="text-sm font-black text-slate-600">← Choose game mode</button><h2 className="mt-3 flex items-center gap-2 text-2xl font-black text-slate-800"><Swords className="text-violet-700"/> Live {LABEL[gameKey]}</h2><p className="mt-1 text-sm font-semibold text-slate-500">Play a private game with a family member on their own device.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><select aria-label="Choose a family opponent" value={opponentId} onChange={(event) => setOpponentId(event.target.value)} className="flex-1 rounded-xl border border-violet-200 px-3 py-2 font-bold"><option value="">Choose a family player</option>{opponents.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button type="button" disabled={!opponentId || busy} onClick={() => void start()} className="rounded-xl bg-violet-700 px-4 py-2 font-black text-white disabled:opacity-50">Start live game</button></div><div className="mt-5 border-t pt-4"><h3 className="font-black text-slate-800">Your {LABEL[gameKey]} games</h3><div className="mt-2 space-y-2">{matches.map((item) => <button key={item.id} type="button" onClick={() => setOpenedId(item.id)} className="flex w-full justify-between rounded-2xl bg-slate-50 p-3 text-left"><span><span className="block font-black">{item.playerOne.name} vs {item.playerTwo.name}</span><span className="text-xs font-bold text-slate-500">{item.status === "active" ? `${item.currentTurn === "player-one" ? item.playerOne.name : item.playerTwo.name} to move` : "Completed"}</span></span><span className="font-black text-violet-700">Open →</span></button>)}{matches.length === 0 && <p className="text-sm font-semibold text-slate-400">No live games yet.</p>}</div></div></section>;
}
